development:
 <<: *default
 database: sinatra_di_dev
 password: password

test:
 <<: *default
 database: sinatra_di_test
 password: password

production:
 <<: *default
 database: sinatra_di_prod
 password: password


default: &default
 host: localhost
 adapter: postgresql
 encoding: UTF8
 username: sinatra_di
 timeout: 5000
 reaping_frequency: 30
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
